entity: smartbite
project_name: smartbite
run_name: resnet_classifier_2505161

dataset:
  train_json: data/processed/food-101/train.json
  val_json: data/processed/food-101/test.json
  test_json: data/processed/food-101/test.json
  images_dir: data/raw/food-101/images
  batch_size: 32

model:
  lr: 0.00001
  num_classes: 101

trainer:
  max_epochs: 8
  accelerator: auto
  devices: auto
  precision: 32

wandb:
  log_model: all
  model_artifact: simonluder/smartbite_resnet_classifier:latest
