name: Build and Push Docker Images

on:
  push:
    branches: [main, fastapi-backend]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Start backend service
        run: |
          docker build -f backend/backend.dockerfile -t smartbite-backend .
          docker run -d \
            --name smartbite-backend \
            -e FATSECRET_API_KEY=${{ secrets.CLIENT_ID }} \
            -e FATSECRET_API_SECRET=${{ secrets.CLIENT_SECRET }} \
            -p 8000:8000 \
            smartbite-backend

      - name: Run tests
        run: |
          echo "Waiting for backend service to be ready..."
          curl --fail --retry 10 --retry-delay 5 http://localhost:8000/api/status
          pytest tests/

      - name: Stop backend service
        if: always()
        run: |
          docker stop smartbite-backend
          docker rm smartbite-backend

  build-and-push:
    needs: tests # ensure tests are run before building images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [backend, dashboard] # run the job for each service

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to GHCR
        uses: docker/login-action@v2 # log in to GitHub Container Registry
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PAT  }}

      - name: Build and push ${{ matrix.service }}
        run: |
          docker build -f ./${{ matrix.service }}/${{ matrix.service }}.dockerfile -t ghcr.io/${{ github.repository }}/${{ matrix.service }}:latest .
          docker push ghcr.io/${{ github.repository }}/${{ matrix.service }}:latest
