name: Build and Push Docker Images

on:
  push:
    branches: [main, fastapi-backend]
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest requests wandb

      - name: Download latest model weights
        env:
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
        run: |
          wandb login $WANDB_API_KEY
          wandb artifact get smartbite/smartbite/best_classifier_model:latest --root backend/src/static_files/

      - name: Build backend Docker image
        run: |
          docker build -f backend/backend.dockerfile -t smartbite-backend .

      - name: Start backend service
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          NUTRITION_API_URL: ${{ secrets.NUTRITION_API_URL }}
        run: |
          docker run -d \
            --name smartbite-backend \
            -e CLIENT_ID \
            -e CLIENT_SECRET \
            -e NUTRITION_API_URL \
            -p 8000:8000 \
            smartbite-backend

      - name: Show backend container logs (debugging)
        run: |
          echo "Fetching logs from smartbite-backend container..."
          docker logs smartbite-backend || true

      - name: Run tests
        run: |
          echo "Waiting for backend service to be ready..."
          curl --fail --retry 10 --retry-delay 5 http://localhost:8000/api/status
          pytest tests/

      - name: Stop backend service
        if: always()
        run: |
          docker stop smartbite-backend
          docker rm smartbite-backend

  build-and-push:
    needs: tests # ensure tests are run before building images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [backend, dashboard] # run the job for each service

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install wandb CLI
        run: pip install wandb

      - name: Download latest model weights
        env:
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
        run: |
          wandb login $WANDB_API_KEY
          wandb artifact get smartbite/smartbite/best_classifier_model:latest --root backend/src/static_files/

      - name: Log in to GHCR
        uses: docker/login-action@v2 # log in to GitHub Container Registry
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PAT  }}

      - name: Build and push ${{ matrix.service }}
        run: |
          docker build -f ./${{ matrix.service }}/${{ matrix.service }}.dockerfile -t ghcr.io/${{ github.repository }}/${{ matrix.service }}:latest .
          docker push ghcr.io/${{ github.repository }}/${{ matrix.service }}:latest
